---
repos:
  - repo: https://github.com/jessp01/pre-commit-golang.git
    rev: v0.5.9
    hooks:
      - id: go-fmt
      # - id: go-imports
      - id: go-vet
      - id: go-lint
      - id: go-critic
      - id: go-ineffassign
      - id: shellcheck
  - repo: https://github.com/crate-ci/typos
    rev: typos-v0.7.4
    hooks:
    - id: typos
