---
repos:
  - repo: https://github.com/jessp01/pre-commit-golang.git
    rev: v0.5.9
    hooks:
      - id: go-fmt
      # - id: go-imports
      - id: go-vet
      - id: go-lint
      - id: go-critic
      - id: go-ineffassign
      - id: shellcheck
  # - repo: https://github.com/crate-ci/typos
  # rev: v1.32.0
  # hooks:
  # - id: typos
  #  stages: [commit]
  #  exclude_types: [yaml]
  #  exclude: go.*
