# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v 
    - name: Test
      run: |
        set -x
        pip install pre-commit || true 
        pre-commit install || cat /home/runner/.cache/pre-commit/pre-commit.log && exit 1
        pre-commit run --all-files || cat /home/runner/.cache/pre-commit/pre-commit.log && exit 2
        go test -v
        sudo ./install_zaje.sh

    #- name: Test
    #run: go test -v 
